apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "event-bot.fullname" . }}-config
  labels:
    {{- include "event-bot.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      env: {{ .Values.env }}
      log_level: {{ .Values.logLevel }}

    valkey:
      addr: {{ .Values.settings.vk_addr }}

    mq:
      enabled: {{ .Values.settings.mq_enabled }}

    webhooks:
      events:
        {{- range .Values.events }}
        - {{ . }}
        {{- end }}
