{{- if .Values.vault.enable }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "event-bot.fullname" . }}-external-secret
  labels:
    {{- include "event-bot.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ include "event-bot.fullname" . }}-external-secret
  data:
    {{- range .Values.vault.secretMappings }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: event-bot
        property: {{ .property }}
    {{- end }}
    {{- if .Values.settings.mq_enabled }}
    {{- range .Values.vault.mqSecretMappings }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: event-bot
        property: {{ .property }}
    {{- end }}
    {{- end }}
{{- end }}